# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-11 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User2',
        ),
    ]
