# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180126_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_total',
            field=models.IntegerField(default=0),
        ),
    ]
