# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20180128_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_line_1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_line_2',
        ),
    ]
