# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-11 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20180128_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default='', max_length=120),
        ),
    ]
