# Generated by Django 2.2 on 2019-07-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_auto_20190714_2016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='subtotal',
        ),
    ]
